### ISSUE TITLE
Wrong changepw command for CM13

### ISSUE THREAD

**Issue by jfeise** [nelenkov/cryptfs-password-manager#15]
On CM13 (maybe also on Android 6), the vdc cryptfs changepw command is wrong, and results in an empty password.
A check of system/vold/CryptCommandListener.cpp shows that the command needs to be
vdc cryptfs password current-password new-password

Update: Removed angle brackets since they are interpreted...

**Comment by nelenkov** [comment]
Probably a CM breaking change, see #14

**Comment by jfeise** [comment]
CM apparently has now support for the original AOSP usage of vold cryptfs back in:
http://review.cyanogenmod.org/#/c/129185/
