### ISSUE TITLE
Please add ACCESS_SUPERUSER to permissions list

### ISSUE THREAD

**Issue by revuwa** [nelenkov/cryptfs-password-manager#6]
I'm using the "declared permission" option of my su-management. That means, that su-request will be only allowed from apps that declare android.permission.ACCESS_SUPERUSER.

So would you please add the following line:
<code>&lt;uses-permission android:name="android.permission.ACCESS_SUPERUSER" /&gt;</code>
to your:
<code>AndroidManifest.xml</code>
in future versions?
[credits / source: https://github.com/kibab/encpasschanger/issues/2]

Thanks in advance for any response.

**Comment by nelenkov** [comment]
This permission is problematic and has been deprecated in SuperSU, which is the only su app this app currently works with on Lollipop. The permission was listed in previous versions, I removed it intentionally.

**Comment by mcdowell36** [comment]
access superuser
