### ISSUE TITLE
Support CM12

### ISSUE THREAD

**Issue by gladiac** [nelenkov/cryptfs-password-manager#7]
Hi,

could you support CM12. It looks like it correctly gains root access but then fails:

```7096 D/su      ( 6233): su invoked.
7097 D/su      ( 6233): starting daemon client 10073 10073
7098 D/su      ( 6235): remote pid: 6233
7099 D/su      ( 6235): remote pts_slave:·
7100 D/su      ( 6235): waiting for child exit
7101 D/su      ( 6238): su invoked.
7102 E/su      ( 6238): SU from: u0_a73
7103 D/su      ( 6238): Checking whether app [uid:10073, pkgName: org.nick.cryptfs.passwdmanager] is allowed to be root
7104 D/VoldCmdListener( 2400): cryptfs getpwtype
7105 D/su      ( 6238): Privilege elevation allowed by appops
7106 D/su      ( 6238): Allowing via appops.
7107 D/su      ( 6238): 10073 /system/bin/app_process32 executing 0 /system/bin/sh using binary /system/bin/sh : sh
7108 D/su      ( 6238): Waiting for pid 6239.
7109 D/su      ( 6241): su invoked.
7110 D/su      ( 6238): Finishing su operation for app [uid:10073, pkgName: org.nick.cryptfs.passwdmanager]
7111 D/su      ( 6235): sending code
7112 D/su      ( 6235): child exited
7113 D/su      ( 6233): client exited 0```

**Comment by nelenkov** [comment]
It's not only a matter of getting root, the default SELinux policy prevents the `vdc` utility from writing to stdout, so the app can't read the result. 

That said, CM supports separate passwords natively (via the Settings menu), so you shouldn't really need this app.

**Comment by bdimcheff** [comment]
I don't think CM12 has the password setting anymore, or at least I couldn't find it.  I was able to install supersu and use cryptfs fine in cm12 tho.

**Comment by nelenkov** [comment]
Yes, it seems the option has been removed, not sure why. It should work fine with SuperSU, but doesn't work with the built-in Superuser.

**Comment by somethingnew2-0** [comment]
I think my PR might have fixed this issue https://github.com/nelenkov/cryptfs-password-manager/pull/9

**Comment by nelenkov** [comment]
Yes, it appears CM have relaxed the SELinux policy, so `supolicy` is not required (still needed on stock though). The updated version should go live in the Play Store soon. Thanks @somethingnew2-0!
